# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b24ca029af752d496f1abe52d318feda191f231cdfd2a9e9d47e421b62043bcfac514b3210f89bbb95852e7d96ebd74ee7ed23c9e8c5790cd21964db060ec3d1

test:
  secret_key_base: 38efc06bd37156726dd31ec40f6284cde6601ea08809b8210cdd447a8cbfa6890489ea82b3cb06e9c277e0904e369c35f746f4fc4a6f37deead7f6b7aafeec44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
